name: Package exe with PyInstaller - Windows

on:
  push:
    paths:
      - 'version'
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get version
      run: echo "STAYIN_VERSION=$(cat version)" >> $GITHUB_ENV
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - run: pip install -r src/requirements.txt pyinstaller
    - run: cd src && pyinstaller --clean -y automator.spec

    - uses: actions/upload-artifact@v2
      with:
        name: stayin exe
        path: "src/dist/*"

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: "zip"
        filename: "stay-in-${{ env.STAYIN_VERSION }}.zip"
        path: "src/dist/stayin.exe"

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        name: "${{ env.STAYIN_VERSION }}"
        artifacts: "stay-in--${{ env.STAYIN_VERSION }}.zip"
        artifactContentType: application/zip
        generateReleaseNotes: True
        token: ${{ secrets.GITHUB_TOKEN }}
